const express = require('express');
const { protect } = require('../middleware/authmiddleware');
const router = express.Router();
const { accessChats, getAllChats, createGroupChat, renameGroup, removeFromGroup, addToGroup } = require('../controller/chats/chatsController');
router.route('/').get(protect, getAllChats);
router.route('/').post(protect, accessChats);
router.route('/group').post(protect, createGroupChat);
router.route('/rename').put(protect, renameGroup);
router.route('/groupremove').put(protect, removeFromGroup);
router.route('/add').put(protect, addToGroup);
module.exports = router;
